### PR TITLE
Update config.js for v2.6 release

### LINKED ISSUE #10: update for v2.6
* add new languages to config.js --`bg`, `scn`, and `lt` are above 33%
* update version to 2.6

### PR DESCRIPTION
**Pull request by pkra**
Update config.js

* update version to 2.6 for v2.6 release
* add bg, scn, lt to config.js

Fixes #10

### CODE REVIEW

**Comment by pkra** [comment]
I wouldn't mind a check of the Lithuanian plural form, cf. http://unicode.org/repos/cldr-tmp/trunk/diff/supplemental/language_plural_rules.html

**Comment by pkra** [comment]
Pushed a few more tweaks to reduce changes to core MathJax later on.

**Comment by dpvc** [comment]
> I wouldn't mind a check of the Lithuanian plural form

Nothing in MathJax currently uses the plural forms anyway, so it is not a big deal.  It looks OK to me, though.

**Comment by pkra** [comment]
> Nothing in MathJax currently uses the plural forms anyway

Got it.

>  It looks OK to me, though.

Thanks!

**Pull request merged**
